language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: O9jfx3ySnQXzkJa/aQnSY1QfkzERKTaLA+ann6Rek068lEtnY2xA2HcAeEq1L3GftTsMqG+4fh4j2QRqhoynR5xp/CGZSKAeeXk4BrDFF3Ayx9C7u60jO5AxvbFXQAgBWujj15sghnEH+j9BBB5zf6uYA6DlCCc1nTF/weSUGGbEWyrl3GMjhwNGcFgq26zCgM/7SMLMDbMrYbp1Tn1xB+xoHiJWFLg78Bf23rE/qKbaTroo4CypVRqQw9vpBWhQf54BfG3nHBFL3/rw384XcTDnuMZuxVAHe2uFps6BXoOPvoEI3A3lgPZPyJ9ROf78Y30+WpF5E8eUWwVuE10G1WHuwOiHN9pqdWw7f2xD05w1/wJBBAHJ18MjFeitHPQJIFQGo6vWPMy2UaCGTMfOCsFLeP0x9Ussya441nNg+nOg4fD3MimZu8iuT1vL6AGue2h/ad9DLuwMtfaYIPMfJv/1R2Uh0UxG6YkQUOWtCMuIaDl72y+pDn/y9el2eo9A+uWPU9DESw7FHeKcHsZg7NNMtrndYwI6x19HCFyYWnYLX3lgaTs6245fGlaTZt1NWV59NrGCVC3cDMEogSCEd4iiX2uOytBukAINxUJRCe1mSgx84zx1z2ats1hF1i3BvpbVmK8sKe96PA7/3Blzes1rMbOUcNzNpiIx6atVUAo=
