language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: J/9McgSNPxbeDzNfj8/p3Ibq3Q684a3RB/N468oCnA3G/Sc1qGBaAscB5+YjnM4YyIs7YI5W66Nk27uCqYoFKNvbyamjZLv3GBgM/KBhH9HJRLiFMJ5qraEzP0iaGMr/KCBXgmAzEj6QQN2kapej0A8+C0YNdtgLAYf03sERVFF9+dzuvfzV2WsghphN8Jl/cJgia5edYxnKX/8SyIV6qfk3O06A5uj9WHYQlqfp4/CfYktINiL109EGeN7EkPniAkWquEUd5g30foUHFDIc9z1xf5UGetXI7+rkllYHqKQilbk7GUnfBVYDF5+VqNy3V2cXDUlOI0f1wo0S6TEC3y+3lUCWQ8fcNEkGcSF5a2ucxzdxg1jVH4xIdXuA1gECZyTGQv56fWXHTu5HmB1wEvc+QqaRb4eWutcbKPSTISnKmO2WfuWV2PW35UuFitErc6JTRNmWcHMDkI4jGdFbONjWck9Q/s6NGpO4PYes4xrPqJQ0aMCW8DeOYfoqZ23OfoRs1dHLsXjQ+EAuD4TCGi0j6ki9WsDVGdR1rdT/qQ3cv/06Htphksm5MWHEdzDD4e3l/mn5R2VdNpyQ0R4kBGKG4RN3Cco0/CAyc7KfkzhHFTpugE+v7rS4SMxpdRVYMtGTak3+7Rys+y2muB+ZayWQJG8qNtjerDDUoWY7sdY=
  app: istic-alertas
